Repository DriveOrbit/DOB_LandingPage, pull requests merged in 2025-02, with the labels that each got.

#1 feat: created responsive navigation bar and add animations
  app/page.tsx
Labels: feature

#3 feat: created the team details section
  app/page.tsx
Labels: feature

#5 feat: basic footer
  app/page.tsx
Labels: feature

#6 feat: modify the hero section and navigation bar
  app/layout.tsx
  app/page.tsx
Labels: enhancement

#8 refactor: change images links and connect nav bar
  app/page.tsx
Labels: enhancement

#9 Secondary footer
  app/page.tsx
Labels: enhancement

#10 refactor: Enhance navbar UI and improve navigation flow
  app/page.tsx
Labels: enhancement

#11 Form
  app/form/page.tsx
  app/page.tsx
Labels: feature

#15 Herohome
  app/page.tsx
  components/ui/background-beams.tsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: enhancement, feature

#16 Background beams
  app/page.tsx
  package-lock.json
  package.json
Labels: feature

#17 feat: add custom animations to the team section and update the packag…
  app/globals.css
  app/page.tsx
  components/ui/animated-testimonials.tsx
  package-lock.json
  package.json
Labels: feature

#19 feat: add custom animations to the team section and update the package dependencies
  app/globals.css
  app/page.tsx
  components/ui/animated-testimonials.tsx
  package-lock.json
  package.json
Labels: enhancement, feature
